### ISSUE TITLE
Dracula Pro for WingIDE?

### ISSUE THREAD

**Issue by tollis-hunt** [sdeibel/dracula-wing#2]
Any chance of the Dracula Pro pallets being available for Wing? I LOVE the Van Helsing version, and its easily the best color pallet for me due to some eye issues I have. I am wondering if this is possible. And thanks for your splendid work! :)

**Comment by sdeibel** [comment]
Tollis Hunt wrote on 4/11/21 2:49 PM:

> Any chance of the Dracula Pro pallets being available for Wing? I LOVE 
> the Van Helsing version, and its easily the best color pallet for me 
> due to some eye issues I have. I am wondering if this is possible. And 
> thanks for your splendid work! :)
>

Wing isn't on the the list of supported apps, although we did add 
support for the original Dracula so it's probably not hard to add to 
Dracula Pro or manually create the configuration from the existing files 
in Dracula Pro (by dropping in the right colors):

https://draculatheme.com/wing/

We're not planning on adding a matching palette to Wing, though, since 
people should be purchasing Dracula Pro to get that.

All the best,

Stephan Deibel
Wing Python IDE | The Intelligent Development Environment for Python

**Comment by tollis-hunt** [comment]
Only reason I ask is because I did pay for it and use it everywhere I can. I'll look at making my own, thanks for the speedy reply! 😄 

Awesome IDE by the way.

**Comment by sdeibel** [comment]
It would be nice if Wing were one of the choices for people that purchased Dracula Pro.  I suppose you could contribute your take on it so it's maintained going forward, if the vendor is willing?

Please let us know if we can help with any problems.
